[package]
name = "route-recognizer"
description = "Recognizes URL patterns with support for dynamic and wildcard segments"
license = "MIT"
repository = "https://github.com/rustasync/route-recognizer"
keywords = ["router", "url"]
edition = "2018"

version = "0.3.1"
authors = ["wycats", "rustasync"]
